'use client'
import './globals.css'
import AuthProvider from './components/AuthProvider/page'


export const metadata = {
  title: 'Shopping Cart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <head>
          <title>Shopping Cart</title>
        </head>
        <body>
            {children}
        </body>
      </html>
    </AuthProvider>
  )
}
